import { Compiler } from './compiler';
import * as filters from './filters';
import { compilerOptions } from './options';
import { plugins } from './plugins';

export interface PrecompileOptions {
  includeRuntime?: boolean;
}

export async function precompileTemplate(
  template: string,
  options: PrecompileOptions = {},
): Promise<string> {
  const mergedOptions = {
    ...compilerOptions,
    filters,
    plugins,
    parsers: {},
    compilers: {},
  };

  // Manually merge plugins
  for (const plugin of plugins) {
    if (plugin.filters) {
      Object.assign(mergedOptions.filters, plugin.filters);
    }

    if (plugin.parsers) {
      Object.assign(mergedOptions.parsers, plugin.parsers);
    }

    if (plugin.compilers) {
      Object.assign(mergedOptions.compilers, plugin.compilers);
    }
  }

  const compiler = new Compiler(mergedOptions);

  await compiler.compile(template);

  const compiledCode = compiler.code;

  if (options.includeRuntime) {
    // Wrap with runtime for standalone execution
    return `// Auto-generated by Janja precompiler
// Do not edit this file manually

${compiledCode}

export default async function render(globals = {}) {
  const escape = (v) => {
    if (v === null || v === undefined) return '';
    if (typeof v === 'object') return JSON.stringify(v);
    return String(v).replace(/[&<>"']/g, c => ({
      '&': '&amp;',
      '<': '&lt;',
      '>': '&gt;',
      '"': '&quot;',
      "'": '&#39;'
    }[c]));
  };

  return await script(globals, escape, ${JSON.stringify(filters)});
}`;
  }

  return compiledCode;
}
