name: NPM publish
permissions:
  id-token: write
  contents: read

on:
  release:
    types: [created]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  npm-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Enable Corepack
        run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm
          registry-url: https://registry.npmjs.org/
      - uses: actions/cache@v4
        with:
          path: node_modules
          key: pnpm-cache-${{ hashFiles('pnpm-lock.yaml') }}
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Build
        run: pnpm build
        working-directory: packages/janja
      - name: Update npm
        run: npm install -g npm@latest
      - name: Publish
        run: npm publish
        working-directory: packages/janja
