name: Release please
permissions:
  contents: read
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
    paths:
      - .release-please-manifest.json
  workflow_dispatch:

jobs:
  release-please:
    runs-on: warp-ubuntu-latest-x64-2x
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GHB_PAT }}
          target-branch: main
