name: Test

on:
  push:
    branches:
      - main
    paths:
      - 'packages/template/**/*'
  pull_request:
    paths:
      - 'packages/template/**/*'

concurrency:
  group: test-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'yarn'
      - name: Enable Corepack
        run: corepack enable
      - uses: actions/cache@v4
        with:
          path: node_modules
          key: yarn-cache-${{ hashFiles('yarn.lock') }}
      - name: Install Dependencies
        run: yarn install --immutable
      - name: Run test
        run: yarn test --coverage
      - name: Vitest Coverage Report
        uses: davelosert/vitest-coverage-report-action@v2.6.0
        with:
          working-directory: './packages/jianjia/'
          json-summary-path: './coverage/coverage-summary.json'
          json-final-path: './coverage/coverage-final.json'
