name: Test
permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches:
      - main
    paths:
      - 'packages/template/**/*'
  pull_request:
    paths:
      - 'packages/template/**/*'

concurrency:
  group: test-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Enable Corepack
        run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'yarn'
      - uses: actions/cache@v4
        with:
          path: node_modules
          key: yarn-cache-${{ hashFiles('yarn.lock') }}
      - name: Install Dependencies
        run: yarn install --immutable
      - name: Run test
        run: yarn test --coverage
